version: "3.8"
services:
  backend:
    build: 
      context: ./ResumeBuilderBackend
    ports:
      - "4292:4292"
  frontend:
    build:
      context: ./ResumeBuilderAngular
    ports:
      - "4200:4200"
    depends_on:
      - backend