apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: resumeai-backend
          image: narsss1234/resumeai-backend:latest
          ports:
            - containerPort: 4292
              name: backend-port
          imagePullPolicy: Always