apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: narsss1234/resumeai-nginx:latest
          ports:
            - containerPort: 80
              name: nginx-port
          imagePullPolicy: Always
      initContainers:
        - name: init-mydb
          image: busybox
          command: ['sh', '-c', 'until nslookup frontend.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for frontend; sleep 2; done;']